//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joseph.ServiceTrayMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Joseph.ServiceTrayMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 6aabfea1-0638-4f58-b8b9-60144643e578 的本地化字符串。
        /// </summary>
        internal static string AppCenterToken {
            get {
                return ResourceManager.GetString("AppCenterToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /AutoStart 的本地化字符串。
        /// </summary>
        internal static string ArgAutoRunUser {
            get {
                return ResourceManager.GetString("ArgAutoRunUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /HideMainWindow 的本地化字符串。
        /// </summary>
        internal static string ArgHideMainWindow {
            get {
                return ResourceManager.GetString("ArgHideMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy/MM/dd HH:mm:ss (UTCz) 的本地化字符串。
        /// </summary>
        internal static string ConstDataTimeFormat {
            get {
                return ResourceManager.GetString("ConstDataTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3000 的本地化字符串。
        /// </summary>
        internal static string ConstDefaultInterval {
            get {
                return ResourceManager.GetString("ConstDefaultInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志文件 (*.txt;*.log)|*.txt;*.log|所有文件 (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string ConstLogFileSelectorFilter {
            get {
                return ResourceManager.GetString("ConstLogFileSelectorFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 windir 的本地化字符串。
        /// </summary>
        internal static string EnviromentNameWindir {
            get {
                return ResourceManager.GetString("EnviromentNameWindir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon IconPending {
            get {
                object obj = ResourceManager.GetObject("IconPending", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon IconRestart {
            get {
                object obj = ResourceManager.GetObject("IconRestart", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon IconStart {
            get {
                object obj = ResourceManager.GetObject("IconStart", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon IconStop {
            get {
                object obj = ResourceManager.GetObject("IconStop", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 32d854d4-d234-4c1a-9634-d0d6aa373935 的本地化字符串。
        /// </summary>
        internal static string MicrosoftGraphApiApplicationId {
            get {
                return ResourceManager.GetString("MicrosoftGraphApiApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .t5qAaAM_BL_mz=zLn2KFtclHAsIHg87 的本地化字符串。
        /// </summary>
        internal static string MicrosoftGraphApiClientSecret {
            get {
                return ResourceManager.GetString("MicrosoftGraphApiClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User.Read+Files.ReadWrite.All 的本地化字符串。
        /// </summary>
        internal static string MicrosoftGraphApiSpoce {
            get {
                return ResourceManager.GetString("MicrosoftGraphApiSpoce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载文件时发生了一个错误。
        ///
        ///详细信息：
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string MsgCloudSyncDownloadFailedError {
            get {
                return ResourceManager.GetString("MsgCloudSyncDownloadFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载成功。 的本地化字符串。
        /// </summary>
        internal static string MsgCloudSyncDownloadSuccess {
            get {
                return ResourceManager.GetString("MsgCloudSyncDownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在云同步页面发生错误。
        ///
        ///详细信息：
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string MsgCloudSyncGeneralError {
            get {
                return ResourceManager.GetString("MsgCloudSyncGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取同步信息时发生了一个错误。
        ///
        ///详细信息：
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string MsgCloudSyncGetLastSyncDateFailedError {
            get {
                return ResourceManager.GetString("MsgCloudSyncGetLastSyncDateFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已从 Service Tray Monitor 中登出 Microsoft 账户。 的本地化字符串。
        /// </summary>
        internal static string MsgCloudSyncMicrosoftAccountLogout {
            get {
                return ResourceManager.GetString("MsgCloudSyncMicrosoftAccountLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 云端配置文件为空。将继续使用本地配置文件。 的本地化字符串。
        /// </summary>
        internal static string MsgCloudSyncNullOrEmptyRemoteFileError {
            get {
                return ResourceManager.GetString("MsgCloudSyncNullOrEmptyRemoteFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 云端配置文件解析失败。将继续使用本地配置文件。 的本地化字符串。
        /// </summary>
        internal static string MsgCloudSyncParseError {
            get {
                return ResourceManager.GetString("MsgCloudSyncParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件时发生了一个错误。
        ///
        ///详细信息：
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string MsgCloudSyncUploadFailedError {
            get {
                return ResourceManager.GetString("MsgCloudSyncUploadFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传成功。 的本地化字符串。
        /// </summary>
        internal static string MsgCloudSyncUploadSuccess {
            get {
                return ResourceManager.GetString("MsgCloudSyncUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件已损坏，将生成新的配置文件。 的本地化字符串。
        /// </summary>
        internal static string MsgConfigFileBroken {
            get {
                return ResourceManager.GetString("MsgConfigFileBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除吗？ 的本地化字符串。
        /// </summary>
        internal static string MsgConfirmDelete {
            get {
                return ResourceManager.GetString("MsgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭主窗口将导致未保存的数据丢失。是否要退出？ 的本地化字符串。
        /// </summary>
        internal static string MsgConfirmMainWindowClose {
            get {
                return ResourceManager.GetString("MsgConfirmMainWindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要保存当前配置？ 的本地化字符串。
        /// </summary>
        internal static string MsgConfirmSave {
            get {
                return ResourceManager.GetString("MsgConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建了检测服务状态时间间隔的配置文件。文件使用默认值（{0}ms）。
        ///如果要修改该值，请直接修改 {1} 文件。
        /// 的本地化字符串。
        /// </summary>
        internal static string MsgCreatedTimerConfigFile {
            get {
                return ResourceManager.GetString("MsgCreatedTimerConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘别名：显示在托盘右键菜单里的别名，尽量短小以减小菜单长度。
        ///日志路径：对于实时将纯文本日志写入磁盘的服务，填写此项以在右键菜单快速查看日志。如果没有日志、不需要或不适用，请留空。
        ///服务名：在 Windows 系统中注册的唯一的 ServiceName。
        ///
        ///要排序列表，请在程序目录下找到 config.json，并修改其中的顺序。
        ///要将程序加入开机启动项，请在启动程序时，加入 /AutoStart 参数。
        ///
        ///调试信息
        ///当前项目的 GUID：{0} 的本地化字符串。
        /// </summary>
        internal static string MsgHelp {
            get {
                return ResourceManager.GetString("MsgHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有有效的日志路径。 的本地化字符串。
        /// </summary>
        internal static string MsgNoVaildLogPath {
            get {
                return ResourceManager.GetString("MsgNoVaildLogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择要删除的配置项。 的本地化字符串。
        /// </summary>
        internal static string MsgSelectItemToBeDeleted {
            get {
                return ResourceManager.GetString("MsgSelectItemToBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务 &quot;{0}&quot; 重启成功 的本地化字符串。
        /// </summary>
        internal static string MsgServiceRestartSuccess {
            get {
                return ResourceManager.GetString("MsgServiceRestartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分服务在启动时出现错误，但其他服务已被正常启动。
        ///
        ///以下是错误的详细内容：
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string MsgServiceStartAllHaveError {
            get {
                return ResourceManager.GetString("MsgServiceStartAllHaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动了所有服务。 的本地化字符串。
        /// </summary>
        internal static string MsgServiceStartAllSuccess {
            get {
                return ResourceManager.GetString("MsgServiceStartAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务 &quot;{0}&quot; 启动成功 的本地化字符串。
        /// </summary>
        internal static string MsgServiceStartSuccess {
            get {
                return ResourceManager.GetString("MsgServiceStartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分服务在停止时出现错误，但其他服务已被正常停止。
        ///
        ///以下是错误的详细内容：
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string MsgServiceStopAllHaveError {
            get {
                return ResourceManager.GetString("MsgServiceStopAllHaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止了所有服务。 的本地化字符串。
        /// </summary>
        internal static string MsgServiceStopAllSuccess {
            get {
                return ResourceManager.GetString("MsgServiceStopAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务 &quot;{0}&quot; 停止成功 的本地化字符串。
        /// </summary>
        internal static string MsgServiceStopSuccess {
            get {
                return ResourceManager.GetString("MsgServiceStopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务 {0} 已启动。 的本地化字符串。
        /// </summary>
        internal static string MsgStartingStartedService {
            get {
                return ResourceManager.GetString("MsgStartingStartedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务 {0} 已停止。 的本地化字符串。
        /// </summary>
        internal static string MsgStoppingStopedService {
            get {
                return ResourceManager.GetString("MsgStoppingStopedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法读取配置文件中的“服务状态检测间隔“（TimerIntervalMs）值。
        ///将使用默认值：{0}（毫秒）。 的本地化字符串。
        /// </summary>
        internal static string MsgUnableToLoadConfigTimerIntervalMs {
            get {
                return ResourceManager.GetString("MsgUnableToLoadConfigTimerIntervalMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 config.json 的本地化字符串。
        /// </summary>
        internal static string PathCloudSyncConfigFile {
            get {
                return ResourceManager.GetString("PathCloudSyncConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \config.txt 的本地化字符串。
        /// </summary>
        internal static string PathConfigFile {
            get {
                return ResourceManager.GetString("PathConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C:\WINDOWS 的本地化字符串。
        /// </summary>
        internal static string PathDefaultWindowsRoot {
            get {
                return ResourceManager.GetString("PathDefaultWindowsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 explorer.exe 的本地化字符串。
        /// </summary>
        internal static string PathExplorerExe {
            get {
                return ResourceManager.GetString("PathExplorerExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \msal_token.cache 的本地化字符串。
        /// </summary>
        internal static string PathMSALTokenCache {
            get {
                return ResourceManager.GetString("PathMSALTokenCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \timer.conf 的本地化字符串。
        /// </summary>
        internal static string PathTimerConfigFile {
            get {
                return ResourceManager.GetString("PathTimerConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServiceTrayMonitor 的本地化字符串。
        /// </summary>
        internal static string RegValueName {
            get {
                return ResourceManager.GetString("RegValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ServicesIcon {
            get {
                object obj = ResourceManager.GetObject("ServicesIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon TaskmgrIcon {
            get {
                object obj = ResourceManager.GetObject("TaskmgrIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 未同步 的本地化字符串。
        /// </summary>
        internal static string UICloudSyncLastSyncStateNotSynced {
            get {
                return ResourceManager.GetString("UICloudSyncLastSyncStateNotSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在传输…… 的本地化字符串。
        /// </summary>
        internal static string UICloudSyncLastSyncStateSyncing {
            get {
                return ResourceManager.GetString("UICloudSyncLastSyncStateSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中…… 的本地化字符串。
        /// </summary>
        internal static string UICloudSyncLoginStateLoading {
            get {
                return ResourceManager.GetString("UICloudSyncLoginStateLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存* 的本地化字符串。
        /// </summary>
        internal static string UISaveButtonContentTextEdited {
            get {
                return ResourceManager.GetString("UISaveButtonContentTextEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string UISaveButtonContentTextNormal {
            get {
                return ResourceManager.GetString("UISaveButtonContentTextNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启 的本地化字符串。
        /// </summary>
        internal static string UITrayMenuItemOperationRestart {
            get {
                return ResourceManager.GetString("UITrayMenuItemOperationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看日志 的本地化字符串。
        /// </summary>
        internal static string UITrayMenuItemOperationShowLog {
            get {
                return ResourceManager.GetString("UITrayMenuItemOperationShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string UITrayMenuItemOperationStart {
            get {
                return ResourceManager.GetString("UITrayMenuItemOperationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string UITrayMenuItemOperationStop {
            get {
                return ResourceManager.GetString("UITrayMenuItemOperationStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取中 的本地化字符串。
        /// </summary>
        internal static string UITrayMenuItemStatusPending {
            get {
                return ResourceManager.GetString("UITrayMenuItemStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态： 的本地化字符串。
        /// </summary>
        internal static string UITrayMenuItemStatusPlaceHolder {
            get {
                return ResourceManager.GetString("UITrayMenuItemStatusPlaceHolder", resourceCulture);
            }
        }
    }
}
